name: CodeQuality
on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - main
      - 'KeY-*'

jobs:
  checkerFramework:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew -DENABLE_NULLNESS=true compileTest

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew --parallel --continue spotlessCheck

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - run: git merge-base HEAD origin/main
      - run: git diff -U0 $(git merge-base HEAD origin/main)

      - name: Build with Gradle
        run: ./gradlew --parallel --continue checkstyleMain

      - name: Copy Sarif
        run: ./gradlew --parallel --continue sarifCopy

      - run: "ls build/sarif-results/*"


      - name: "Job summary"
        run: "cat */build/reports/checkstyle/main.md >> $GITHUB_STEP_SUMMARY"

      - name: Upload checkstyle report
        uses: actions/upload-artifact@v4
        if: (success() || failure())
        with:
          name: checkstyle-report
          path: "**/build/reports/checkstyle/main.html"

      - name: "Publish in Github code scanning"
        uses: github/codeql-action/upload-sarif@v3
        if: (success() || failure())
        with:
          sarif_file: "build/sarif-results"
